apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your-root-password
        - name: MYSQL_DATABASE
          value: your-database-name
        - name: MYSQL_USER
          value: your-mysql-user
        - name: MYSQL_PASSWORD
          value: your-mysql-password
        ports:
        - containerPort: 3306
