apiVersion: apps/v1
kind: Deployment
metadata: mysql
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123qwe
        - name: MYSQL_DATABASE
          value: mysqldb
        - name: MYSQL_USER
          value: mysqldb
        - name: MYSQL_PASSWORD
          value: 123qwe  
        ports:
        - containerPort: 3306  
